import { Category, Product, Slider, Promocode } from "@/types/database";

export const DEFAULT_CATEGORIES: Category[] = [
  {
    id: "cat-bolgarkalar",
    name: "Bolgarkalar (UGL)",
    slug: "bolgarkalar",
    description: "Professional burchakli silliqlash mashinalari (115mm, 125mm, 150mm, 230mm)",
    image_url: "https://images.unsplash.com/photo-1504148455328-c376907d081c?q=80&w=800&auto=format&fit=crop",
    is_active: true,
    product_count: 4,
    created_at: "2025-01-01T00:00:00.000Z",
  },
  {
    id: "cat-drellar-shurupovyortlar",
    name: "Drellar va Shurupovyortlar",
    slug: "drellar-va-shurupovyortlar",
    description: "Akkumulyatorli va tarmoqli drellar, cho'tkasiz shurupovyortlar, gaykavyortlar",
    image_url: "https://images.unsplash.com/photo-1572981779307-38b8cabb2407?q=80&w=800&auto=format&fit=crop",
    is_active: true,
    product_count: 4,
    created_at: "2025-01-01T00:00:00.000Z",
  },
  {
    id: "cat-perforatorlar",
    name: "Perforatorlar va Otboyniklar",
    slug: "perforatorlar",
    description: "SDS-Plus va SDS-Max perforatorlar, beton o'yuvchi kuchli bolg'alar",
    image_url: "https://images.unsplash.com/photo-1586864387967-d02ef85d93e8?q=80&w=800&auto=format&fit=crop",
    is_active: true,
    product_count: 3,
    created_at: "2025-01-01T00:00:00.000Z",
  },
  {
    id: "cat-svarka",
    name: "Payvandlash (Svarka) apparatlari",
    slug: "svarka-apparatlari",
    description: "Invertorli IGBT payvandlash apparatlari, yarim-avtomatlar, elektrodlar va niqoblar",
    image_url: "https://images.unsplash.com/photo-1617791160588-241658c0f566?q=80&w=800&auto=format&fit=crop",
    is_active: true,
    product_count: 2,
    created_at: "2025-01-01T00:00:00.000Z",
  },
  {
    id: "cat-lazer-olchov",
    name: "Lazer va O'lchov asboblari",
    slug: "lazer-uravenlar",
    description: "3D va 4D yashil nurli lazer uravenlar, lazerli optik ruletkalar",
    image_url: "https://images.unsplash.com/photo-1581092580497-e0d23cbdf1dc?q=80&w=800&auto=format&fit=crop",
    is_active: true,
    product_count: 2,
    created_at: "2025-01-01T00:00:00.000Z",
  },
  {
    id: "cat-aksessuarlar",
    name: "Aksessuarlar va Jihozlar",
    slug: "aksessuarlar",
    description: "Sverlolar, kesuvchi olmos disklar, akkumulyatorlar va ehtiyot qismlar",
    image_url: "https://images.unsplash.com/photo-1530124566582-a618bc2615dc?q=80&w=800&auto=format&fit=crop",
    is_active: true,
    product_count: 1,
    created_at: "2025-01-01T00:00:00.000Z",
  },
];

export const DEFAULT_PRODUCTS: Product[] = [
  {
    id: "p-veral-ruletka-5m",
    name: "VERAL Electric 5 metrli o'lchov tasmasi (Ruletka)",
    slug: "veral-electric-5m-ruletka",
    description: "VERAL Electric — professional o'lchov ishlari uchun yuqori sifatli 5 metrli ruletka. Lentasining qalinligi 19mm, aniq va yorqin shkalaga ega. Ergonomik kauchuk korpusi sirpanib ketishdan va zarbadan himoya qiladi. Avtomatik qulflanish funksiyasi ishlashni osonlashtiradi.",
    price: 20000,
    old_price: 30000,
    discount: 33,
    category_id: "cat-lazer-olchov",
    brand: "VERAL electric",
    stock: 50,
    sku: "VRL-5M-19",
    rating: 5.0,
    reviews_count: 12,
    image: "/products/veral_5m.jpg",
    images: [],
    specifications: {
      "O'lchov uzunligi": "5 metr",
      "Tasma kengligi": "19 mm",
      "Material": "ABS plastik + Kauchuk",
      "Korpus xususiyati": "Zarbaga chidamli",
      "Avto-qulflash": "Mavjud"
    },
    mechanism: "Mexanik",
    is_active: true,
    is_new: true,
    created_at: "2025-01-26T10:00:00.000Z",
    updated_at: "2025-01-26T10:00:00.000Z",
  },
  {
    id: "p-biyoti-byt2602",
    name: "BIYOTI BYT-2602 Perforator (Rotary Hammer)",
    slug: "biyoti-byt-2602-perforator",
    description: "BIYOTI BYT-2602 — uy va yarim professional qurilish ishlari uchun mo'ljallangan kuchli perforator (otboynik). U 3 ta rejimda ishlaydi: burg'ulash, zarbli burg'ulash va o'yish. Komplektda mustahkam plastik keys, qo'shimcha tutqich, chuqurlik o'lchagich, 3 ta SDS-plus pichoq va 2 ta iskana (zubilo) mavjud. Yuqori sifatli Yevropa standarti asosida ishlab chiqarilgan.",
    price: 460000,
    old_price: 520000,
    discount: 11,
    category_id: "cat-perforatorlar", 
    brand: "BIYOTI",
    stock: 25,
    sku: "BYT-2602",
    rating: 4.8,
    reviews_count: 15,
    image: "/products/biyoti_byt2602.png",
    images: [],
    specifications: {
      "Ish rejimlari": "3 ta rejim (Teshish, Zarbali teshish, O'yish)",
      "Patron turi": "SDS-Plus",
      "Komplektatsiya": "Keys, 3 ta sverlo, 2 ta zubilo",
      "Standart": "Made for EURO",
      "Quvvat turi": "Tarmoqli (220V)"
    },
    mechanism: "Elektr",
    is_active: true,
    is_new: true,
    created_at: "2025-01-26T10:15:00.000Z",
    updated_at: "2025-01-26T10:15:00.000Z",
  },
  {
    id: "p-adegso-knife-10289",
    name: "ADEGSO 10289 Kantselyariya/Oboy pichog'i",
    slug: "adegso-oboy-pichogi-10289",
    description: "ADEGSO (Model: 10289) — qog'oz, karton, oboy va boshqa materiallarni kesish uchun mo'ljallangan yuqori sifatli 'ustalar tanlovi' pichog'i. Pichoqning uchini sindirib, doimiy o'tkir holatda ishlatish mumkin (Snap-off blade). Korpusi qulay ushlash uchun maxsus teksturali dizaynga ega.",
    price: 10000,
    old_price: 15000,
    discount: 33,
    category_id: "cat-aksessuarlar", 
    brand: "ADEGSO",
    stock: 100,
    sku: "ADG-10289",
    rating: 4.9,
    reviews_count: 8,
    image: "/products/adegso_knife_10289.png",
    images: [],
    specifications: {
      "Pichoq turi": "Sindirib yangilanadigan (Snap-off)",
      "Vazifasi": "Oboy, qog'oz, karton kesish",
      "Korpus materiali": "Qattiq plastmassa + rezina qo'shimchalar",
      "Model": "10289"
    },
    mechanism: "Mexanik",
    is_active: true,
    is_new: true,
    created_at: "2025-01-26T10:20:00.000Z",
    updated_at: "2025-01-26T10:20:00.000Z",
  },
  {
    id: "p-adegso-knife-10287",
    name: "ADEGSO 10287 Buklanadigan Oboy pichog'i (Raskladnoy)",
    slug: "adegso-oboy-pichogi-buklanadigan-10287",
    description: "ADEGSO (Model: 10287) — ixcham va qulay, buklanadigan (raskladnoy) oboy pichog'i. Pichoq uchi trapez shaklida bo'lib, o'ta o'tkir kesish xususiyatiga ega. Komplektda qo'shimcha zaxira lezviyalar saqlanadigan kichik kassetasi ham bor. 'Ustalar tanlovi' toifasiga kiruvchi yuqori sifatli asbob.",
    price: 30000,
    old_price: 40000,
    discount: 25,
    category_id: "cat-aksessuarlar", 
    brand: "ADEGSO",
    stock: 75,
    sku: "ADG-10287",
    rating: 5.0,
    reviews_count: 12,
    image: "/products/adegso_knife_10287.png",
    images: [],
    specifications: {
      "Pichoq turi": "Buklanadigan (Raskladnoy / Yig'iluvchi)",
      "Vazifasi": "Oboy, qog'oz, gipsokarton, linoleum kesish",
      "Komplektatsiya": "Pichoq + Zaxira pichoqchalar (lezviya)",
      "Model": "10287"
    },
    mechanism: "Mexanik",
    is_active: true,
    is_new: true,
    created_at: "2025-01-26T10:25:00.000Z",
    updated_at: "2025-01-26T10:25:00.000Z",
  },
  {
    id: "p-rur-r1817",
    name: "RUR R1817 Indikatorli Otvyortka (Tok tekshirgich)",
    slug: "rur-r1817-indikatorli-otvyortka",
    description: "RUR (Model: R1817) — elektr toki bor-yo'qligini xavfsiz va aniq tekshirish uchun mo'ljallangan indikatorli otvyortka. Uch qismi yuqori sifatli qotishmadan qilingan bo'lib, oddiy otvyortka sifatida ham ishlatish mumkin. Chirog'i yorqin yonadi va tutqichi qulay plastikdan ishlangan.",
    price: 12000,
    old_price: 18000,
    discount: 33,
    category_id: "cat-aksessuarlar", 
    brand: "RUR",
    stock: 120,
    sku: "RUR-R1817",
    rating: 4.8,
    reviews_count: 22,
    image: "/products/rur_r1817.png",
    images: [],
    specifications: {
      "Turi": "Indikatorli (Tester)",
      "Vazifasi": "Elektr toki mavjudligini tekshirish",
      "Model": "R1817",
      "Material": "Izolyatsiyalangan plastmassa va po'lat"
    },
    mechanism: "Qo'l asbobi",
    is_active: true,
    is_new: true,
    created_at: "2025-01-26T10:30:00.000Z",
    updated_at: "2025-01-26T10:30:00.000Z",
  },
  {
    id: "p-rur-r3039",
    name: "RUR R3039 Krokodil (Ploskogubsi / Klyuch)",
    slug: "rur-r3039-krokodil-ploskogubsi",
    description: "RUR (Model: R3039) — santexnika va mexanika ishlari uchun mo'ljallangan universal sozlanuvchi qisqich (krokodil / gazoviy klyuch). Turli o'lchamdagi truba va gaykalarni mahkam siqish uchun ko'p pog'onali sozlash mexanizmiga ega. Yuqori mustahkamlikdagi po'latdan ishlangan, tutqichi sirpanmaydigan qoplamali.",
    price: 95000,
    old_price: 120000,
    discount: 21,
    category_id: "cat-aksessuarlar", 
    brand: "RUR",
    stock: 60,
    sku: "RUR-R3039",
    rating: 5.0,
    reviews_count: 18,
    image: "/products/rur_r3039.png",
    images: [],
    specifications: {
      "Turi": "Sozlanuvchi qisqich (Krokodil)",
      "Model": "R3039",
      "Material": "Yuqori sifatli karbonli po'lat",
      "Tutqich": "Sirpanmaydigan, ergonomik qoplama",
      "Qo'llanilishi": "Santexnika, mexanika, ta'mirlash"
    },
    mechanism: "Qo'l asbobi",
    is_active: true,
    is_new: true,
    created_at: "2025-01-26T10:35:00.000Z",
    updated_at: "2025-01-26T10:35:00.000Z",
  },
  {
    id: "p-eafixs-sekator",
    name: "EAFIXS Bog' qaychisi (Sekator / Pruning shears)",
    slug: "eafixs-bog-qaychisi-sekator",
    description: "EAFIXS Professional Tools — daraxt shoxlari, uzum toklarini va gul butalarini kesish uchun mo'ljallangan yuqori sifatli sekator. Qalinligi 20mm gacha bo'lgan shoxlarni osonlik bilan qirqadi. SKS+ sifatli po'latdan ishlangan, tutqichi ergonomik va sirpanmaydi. Sifat kafolati (Industrial / TUV GS).",
    price: 55000,
    old_price: 70000,
    discount: 21,
    category_id: "cat-aksessuarlar", 
    brand: "EAFIXS",
    stock: 80,
    sku: "EAF-SEKATOR",
    rating: 4.9,
    reviews_count: 14,
    image: "/products/eafixs_sekator.png",
    images: [],
    specifications: {
      "Kesish diametri": "20 mm gacha",
      "Pichoq materiali": "SKS+ Yuqori sifatli po'lat",
      "Vazifasi": "Bog'dorchilik, shoxlarni kesish",
      "Sifat standarti": "TUV GS / Industrial",
      "Tutqich": "Sirpanmaydigan qoplama, qulflanuvchi"
    },
    mechanism: "Qo'l asbobi",
    is_active: true,
    is_new: true,
    created_at: "2025-01-26T10:40:00.000Z",
    updated_at: "2025-01-26T10:40:00.000Z",
  },
  {
    id: "p-rur-r1816",
    name: "RUR R1816 Elektron Indikatorli Otvyortka (Raqamli Displey)",
    slug: "rur-r1816-elektron-indikator",
    description: "RUR (Model: R1816) — tok kuchlanishini (12-250V) raqamli displeyda aniq ko'rsatuvchi elektron indikator-otvyortka. Dark Vision funksiyasi tufayli qorong'i joylarda ham ko'rsatkichlarni bemalol o'qish mumkin. Elektriklar va uy ustalari uchun juda qulay va zamonaviy asbob.",
    price: 40000,
    old_price: 55000,
    discount: 27,
    category_id: "cat-aksessuarlar", 
    brand: "RUR",
    stock: 90,
    sku: "RUR-R1816",
    rating: 4.9,
    reviews_count: 17,
    image: "/products/rur_r1816.png",
    images: [],
    specifications: {
      "Turi": "Elektron indikator (Tester)",
      "Kuchlanish diapazoni": "AC/DC 12V-250V",
      "Displey": "Raqamli LCD (Dark Vision)",
      "Vazifasi": "Tokni va kuchlanishni tekshirish",
      "Model": "R1816"
    },
    mechanism: "Elektron",
    is_active: true,
    is_new: true,
    created_at: "2025-01-26T10:45:00.000Z",
    updated_at: "2025-01-26T10:45:00.000Z",
  },
  {
    id: "p-rur-r1813",
    name: "RUR R1813 Raqamli Indikatorli Otvyortka (Digital Voltage Tester)",
    slug: "rur-r1813-raqamli-indikator",
    description: "RUR (Model: R1813) — tok kuchlanishini LCD displeyda ko'rsatadigan raqamli indikator-tester. Oddiy indikatorlarga qaraganda qulayroq va aniqroq tekshiradi (12V-250V). Ixcham dizayn va sifatli RUR Tools mahsuloti.",
    price: 30000,
    old_price: 40000,
    discount: 25,
    category_id: "cat-aksessuarlar", 
    brand: "RUR",
    stock: 150,
    sku: "RUR-R1813",
    rating: 4.8,
    reviews_count: 21,
    image: "/products/rur_r1813.png",
    images: [],
    specifications: {
      "Turi": "Raqamli indikator (Voltage Tester)",
      "Kuchlanish diapazoni": "12V - 250V AC/DC",
      "Displey": "LCD displey",
      "Model": "R1813"
    },
    mechanism: "Elektron",
    is_active: true,
    is_new: true,
    created_at: "2025-01-26T10:50:00.000Z",
    updated_at: "2025-01-26T10:50:00.000Z",
  },
  {
    id: "p-roma-ht535",
    name: "ROMA TOOLS HT-535 Qurilish Quloqchini (Naushnik)",
    slug: "roma-tools-ht535-qurilish-quloqchini",
    description: "ROMA TOOLS (Model: HT-535) — baland shovqinli qurilish, ta'mirlash va ishlab chiqarish sexlarida ishlash uchun mo'ljallangan himoya quloqchini. Quloqni mukammal yopib turuvchi yumshoq yostiqchalari va boshga moslab sozlanuvchi qulay yoyi (dujkasi) bor. Eshitish qobiliyatini asrash uchun muhim himoya vositasi.",
    price: 35000,
    old_price: 45000,
    discount: 22,
    category_id: "cat-aksessuarlar", 
    brand: "ROMA TOOLS",
    stock: 200,
    sku: "RMA-HT535",
    rating: 5.0,
    reviews_count: 34,
    image: "/products/roma_ht535.png",
    images: [],
    specifications: {
      "Turi": "Qurilish himoya quloqchini (Shumoizolyatsiya)",
      "Model": "HT-535",
      "Xususiyati": "Sozlanuvchi yoy, yumshoq yostiqchalar",
      "Vazifasi": "Baland shovqindan himoya qilish"
    },
    mechanism: "Himoya vositasi",
    is_active: true,
    is_new: true,
    created_at: "2025-01-26T10:55:00.000Z",
    updated_at: "2025-01-26T10:55:00.000Z",
  },
  {
    id: "p-adegso-ad50511",
    name: "ADEGSO AD-50511 Otvyortkalar to'plami (8 dona)",
    slug: "adegso-ad50511-otvyortkalar-toplami",
    description: "ADEGSO (Model: 50511) — 'Ustalar tanlovi' qatoriga kiruvchi 8 ta har xil o'lchamdagi professional otvyortkalar to'plami. Katta, o'rtacha va kalta (bochka) otvyortkalarni o'z ichiga oladi. Magnitlangan uchi, ergonomik va sirpanmaydigan tutqichlari bilan ishlash uchun juda qulay.",
    price: 95000,
    old_price: 120000,
    discount: 21,
    category_id: "cat-aksessuarlar", 
    brand: "ADEGSO",
    stock: 50,
    sku: "ADG-50511",
    rating: 4.9,
    reviews_count: 14,
    image: "/products/adegso_screwdrivers_50511.png",
    images: [],
    specifications: {
      "To'plam tarkibi": "8 dona (Katta, kichik, kalta otvyortkalar)",
      "Uch qismi": "Magnitlangan (krestovoy va ploskiy)",
      "Tutqich": "Sirpanmaydigan kauchuk + plastmassa",
      "Model": "AD-50511"
    },
    mechanism: "Qo'l asbobi",
    is_active: true,
    is_new: true,
    created_at: "2025-01-26T11:00:00.000Z",
    updated_at: "2025-01-26T11:00:00.000Z",
  },
  {
    id: "p-adegso-ad50513",
    name: "ADEGSO AD-50513 Tok o'tkazmaydigan Otvyortkalar to'plami (5 dona)",
    slug: "adegso-ad50513-dielektrik-otvyortkalar",
    description: "ADEGSO (Model: 50513) — 'Ustalar tanlovi' qatoriga kiruvchi 5 ta har xil o'lchamdagi dielektrik (tok o'tkazmaydigan) otvyortkalar to'plami. Elektromontaj ishlari uchun maxsus mo'ljallangan bo'lib, xavfsiz ishlashni ta'minlaydi. Ergonomik qizil-sariq tutqich va to'liq izolyatsiya qilingan stervenga ega.",
    price: 75000,
    old_price: 95000,
    discount: 21,
    category_id: "cat-aksessuarlar", 
    brand: "ADEGSO",
    stock: 60,
    sku: "ADG-50513",
    rating: 5.0,
    reviews_count: 18,
    image: "/products/adegso_screwdrivers_50513.png",
    images: [],
    specifications: {
      "To'plam tarkibi": "5 dona (Krestovoy va ploskiy)",
      "Izolyatsiya": "Dielektrik (tok o'tkazmaydi)",
      "Qo'llanilishi": "Elektromontaj va tok ostida ishlash",
      "Model": "AD-50513"
    },
    mechanism: "Qo'l asbobi",
    is_active: true,
    is_new: true,
    created_at: "2025-01-26T11:05:00.000Z",
    updated_at: "2025-01-26T11:05:00.000Z",
  },
  {
    id: "p-adegso-ad50211",
    name: "ADEGSO AD-50211 Universal Hop-Shop Klyuch (2 dona)",
    slug: "adegso-ad50211-hop-shop-klyuch",
    description: "ADEGSO (Model: 50211) — 'Ustalar tanlovi' qatoridagi universal klyuchlar to'plami (Hop-Shop klyuch / Snap'n Grip). To'plamda 2 ta har xil o'lchamdagi klyuch bor bo'lib, ular har qanday shakldagi (kvadrat, dumaloq, oltiburchak) gayka va trubkalarni avtomatik ravishda mahkam qisib oladi. Santexnika va avto ta'mirlash uchun juda qulay.",
    price: 55000,
    old_price: 70000,
    discount: 21,
    category_id: "cat-aksessuarlar", 
    brand: "ADEGSO",
    stock: 80,
    sku: "ADG-50211",
    rating: 4.8,
    reviews_count: 22,
    image: "/products/adegso_wrench_50211.png",
    images: [],
    specifications: {
      "To'plam tarkibi": "2 dona (Katta va kichik klyuch)",
      "Turi": "Universal o'zi qisuvchi klyuch",
      "Qo'llanilishi": "Santexnika, mexanika, ro'zg'or ishlari",
      "Model": "AD-50211"
    },
    mechanism: "Qo'l asbobi",
    is_active: true,
    is_new: true,
    created_at: "2025-01-26T11:10:00.000Z",
    updated_at: "2025-01-26T11:10:00.000Z",
  },
  {
    id: "p-rur-r3038",
    name: "RUR R3038 Krokodil (Sozlanuvchi Ploskogubsi)",
    slug: "rur-r3038-krokodil",
    description: "RUR (Model: R3038) — yuqori sifatli 'Krokodil' (sozlanuvchi ploskogubsi / water pump pliers). Santexnika ishlari va trubalarni qisish uchun juda qulay. Qattiq qotishmali jag'lari va sirpanmaydigan ko'k-kulrang tutqichlari bilan ishonchli ushlashni ta'minlaydi. Turli o'lchamlarga moslashish uchun ko'p pog'onali mexanizmga ega.",
    price: 65000,
    old_price: 85000,
    discount: 23,
    category_id: "cat-aksessuarlar", 
    brand: "RUR",
    stock: 75,
    sku: "RUR-R3038",
    rating: 5.0,
    reviews_count: 16,
    image: "/products/rur_krokodil_r3038.png",
    images: [],
    specifications: {
      "Turi": "Sozlanuvchi qisqich (Krokodil)",
      "Qo'llanilishi": "Santexnika va mexanika",
      "Material": "Yuqori chidamli qotishma po'lat",
      "Model": "R3038"
    },
    mechanism: "Qo'l asbobi",
    is_active: true,
    is_new: true,
    created_at: "2025-01-26T11:15:00.000Z",
    updated_at: "2025-01-26T11:15:00.000Z",
  },
  {
    id: "p-rur-r3049",
    name: "RUR R3049 Kabel Tozalagich (Stripping Crimping Pliers)",
    slug: "rur-r3049-kabel-tozalagich",
    description: "RUR (Model: R3049) — elektr simlari va kabellarni izolyatsiyasidan tozalash hamda siqish (krimpovka) uchun mo'ljallangan maxsus asbob. Elektriklar uchun juda zarur bo'lgan bu asbob simning ichiga shikast yetkazmasdan sirtini tozalaydi. Sirpanmaydigan qulay tutqichga ega.",
    price: 85000,
    old_price: 110000,
    discount: 22,
    category_id: "cat-aksessuarlar", 
    brand: "RUR",
    stock: 85,
    sku: "RUR-R3049",
    rating: 4.9,
    reviews_count: 24,
    image: "/products/rur_stripper_r3049.png",
    images: [],
    specifications: {
      "Turi": "Kabel tozalagich va siquvchi (Stripper)",
      "Qo'llanilishi": "Elektromontaj, simlarni tozalash",
      "Material": "Yuqori sifatli po'lat",
      "Model": "R3049"
    },
    mechanism: "Qo'l asbobi",
    is_active: true,
    is_new: true,
    created_at: "2025-01-26T11:20:00.000Z",
    updated_at: "2025-01-26T11:20:00.000Z",
  },
  {
    id: "p-rur-r2344",
    name: "RUR R2344 Kabel Tozalagich (Wire Stripper)",
    slug: "rur-r2344-kabel-tozalagich",
    description: "RUR (Model: R2344) — sim va kabellarni tez va aniq tozalash uchun mo'ljallangan qulay asbob. Simning turli diametrlariga moslashtirilgan o'yiqlari yordamida ishlash juda oson. O'tkir po'lat pichog'i va rezinali qulay tutqichi bilan ajralib turadi.",
    price: 45000,
    old_price: 60000,
    discount: 25,
    category_id: "cat-aksessuarlar", 
    brand: "RUR",
    stock: 120,
    sku: "RUR-R2344",
    rating: 4.8,
    reviews_count: 19,
    image: "/products/rur_stripper_r2344.png",
    images: [],
    specifications: {
      "Turi": "Kabel tozalagich (Wire Stripper)",
      "Qo'llanilishi": "Sim izolyatsiyasini tozalash",
      "Model": "R2344",
      "Material": "Maxsus ishlov berilgan po'lat"
    },
    mechanism: "Qo'l asbobi",
    is_active: true,
    is_new: true,
    created_at: "2025-01-26T11:25:00.000Z",
    updated_at: "2025-01-26T11:25:00.000Z",
  },
  {
    id: "p-adegso-ad40221",
    name: "ADEGSO 30W Payalnik (Soldering Iron)",
    slug: "adegso-ad40221-payalnik-30w",
    description: "ADEGSO (Model: 40221) — elektronika va mayda ta'mirlash ishlari uchun mo'ljallangan 30 Vt quvvatli sifatli payalnik (kavshar). Tez qiziydi va issiqlikni yaxshi ushlaydi. 'Ustalar tanlovi' toifasiga kiruvchi ishonchli va xavfsiz elektr asbob.",
    price: 65000,
    old_price: 85000,
    discount: 23,
    category_id: "cat-aksessuarlar", 
    brand: "ADEGSO",
    stock: 90,
    sku: "ADG-40221",
    rating: 4.8,
    reviews_count: 15,
    image: "/products/adegso_soldering_40221.png",
    images: [],
    specifications: {
      "Quvvati": "30 Vt (Watt)",
      "Turi": "Elektr payalnik (Soldering iron)",
      "Qo'llanilishi": "Elektronika ta'mirlash",
      "Model": "AD-40221"
    },
    mechanism: "Elektr asbob",
    is_active: true,
    is_new: true,
    created_at: "2025-01-26T11:30:00.000Z",
    updated_at: "2025-01-26T11:30:00.000Z",
  },
  {
    id: "p-biyoti-byt1337",
    name: "BIYOTI BYT-1337 Devor Kesuvchi (Shtroborez)",
    slug: "biyoti-byt1337-shtroborez",
    description: "BIYOTI BYT-1337 — professional devor kesuvchi (shtroborez). Elektr simlari, trubalar va kabellar uchun devorlarda ariqcha (shtroba) ochishga mo'ljallangan. 1500 Vt quvvatli kuchli motor, 125mm disk va qulay dizayn ishlashni osonlashtiradi. Suv ulab ishlash imkoniyati mavjud (chang chiqarmaslik uchun).",
    price: 1100000,
    old_price: 1300000,
    discount: 15,
    category_id: "cat-bolgarkalar", 
    brand: "BIYOTI",
    stock: 12,
    sku: "BYT-1337",
    rating: 4.9,
    reviews_count: 11,
    image: "/products/biyoti_shtroborez_byt1337.png",
    images: [],
    specifications: {
      "Quvvati": "1500 Vt (Watt)",
      "Disk diametri": "125 mm",
      "Turi": "Devor kesuvchi (Shtroborez)",
      "Vazifasi": "Beton, g'isht va tosh kesish",
      "Model": "BYT-1337"
    },
    mechanism: "Elektr asbob",
    is_active: true,
    is_new: true,
    created_at: "2025-01-26T11:35:00.000Z",
    updated_at: "2025-01-26T11:35:00.000Z",
  },
  {
    id: "p-biyoti-battery-16-8v",
    name: "BIYOTI 16.8V Li-ION Akkumulyator (Battery Pack)",
    slug: "biyoti-16-8v-li-ion-akkumulyator",
    description: "BIYOTI — 16.8V kuchlanishli litiy-ion (Li-ION) akkumulyator blok. BIYOTI brendining shurupovyortlari va boshqa simsiz asboblari uchun maxsus (Power Share) mo'ljallangan. 100% original, uzoq muddat xizmat qiladi va tez quvvat oladi.",
    price: 65000,
    old_price: 85000,
    discount: 23,
    category_id: "cat-aksessuarlar", 
    brand: "BIYOTI",
    stock: 200,
    sku: "BYT-BAT-168V",
    rating: 4.8,
    reviews_count: 42,
    image: "/products/biyoti_battery_16v.png",
    images: [],
    specifications: {
      "Turi": "Li-ION Akkumulyator",
      "Kuchlanish": "16.8V",
      "Mosligi": "BIYOTI asboblari uchun",
      "Sifat": "100% Original"
    },
    mechanism: "Akkumulyator",
    is_active: true,
    is_new: true,
    created_at: "2025-01-26T11:40:00.000Z",
    updated_at: "2025-01-26T11:40:00.000Z",
  },
  {
    id: "p-teh-th8516",
    name: "TEH TH8516 Otboynik (Отбойный молоток) 50J",
    slug: "teh-th8516-otboynik-50j",
    description: "TEH (Model: TH8516) — og'ir qurilish va buzish ishlari uchun mo'ljallangan juda kuchli otboynik (perforator). Zarba kuchi 50 Joul bo'lib, beton, asfalt va toshlarni osongina maydalaydi. Zarbalar chastotasi daqiqasiga 1900 marta. Sanoat darajasidagi asbob.",
    price: 2250000,
    old_price: 2600000,
    discount: 13,
    category_id: "cat-perforatorlar", 
    brand: "TEH",
    stock: 10,
    sku: "TH-8516",
    rating: 5.0,
    reviews_count: 8,
    image: "/products/teh_otboynik_th8516.png",
    images: [],
    specifications: {
      "Zarba kuchi": "50 J",
      "Zarbalar soni": "1900 zarba/daq",
      "Quvvati": "1600 Vt (rasmda 160W yozilgani xato bo'lishi mumkin)",
      "Turi": "Og'ir otboynik (Buzuvchi bolg'a)",
      "Tarmoq": "220V/50HZ"
    },
    mechanism: "Elektr asbob",
    is_active: true,
    is_new: true,
    created_at: "2025-01-26T11:45:00.000Z",
    updated_at: "2025-01-26T11:45:00.000Z",
  }
];

export const DEFAULT_SLIDERS: Slider[] = [
  {
    id: "s1",
    title: "Professional Bolgarkalar (UGL)",
    subtitle: "DeWalt, Bosch, Makita va Crown burchakli silliqlash mashinalari. Yuqori quvvat va 1 yil kafolat.",
    image_url: "https://images.unsplash.com/photo-1504148455328-c376907d081c?q=80&w=1920&auto=format&fit=crop",
    button_text: "Bolgarkalarni ko'rish",
    link: "/categories/bolgarkalar",
    sort_order: 1,
    is_active: true,
    created_at: "2025-01-01T00:00:00.000Z",
  },
  {
    id: "s2",
    title: "Akkumulyatorli Shurupovyortlar",
    subtitle: "Kuchli motor, 2 ta litiy batareya va zarbli rejim. Barcha montaj va qurilish ishlari uchun.",
    image_url: "https://images.unsplash.com/photo-1572981779307-38b8cabb2407?q=80&w=1920&auto=format&fit=crop",
    button_text: "Shurupovyortlar",
    link: "/categories/drellar-va-shurupovyortlar",
    sort_order: 2,
    is_active: true,
    created_at: "2025-01-01T00:00:00.000Z",
  },
  {
    id: "s3",
    title: "Invertorli Payvandlash (Svarka)",
    subtitle: "Resanta, Edon va Total svarka apparatlari. Barqaror yoy, qizib ketishdan himoya va ixcham korpus.",
    image_url: "https://images.unsplash.com/photo-1617791160588-241658c0f566?q=80&w=1920&auto=format&fit=crop",
    button_text: "Svarka apparatlari",
    link: "/categories/svarka-apparatlari",
    sort_order: 3,
    is_active: true,
    created_at: "2025-01-01T00:00:00.000Z",
  },
  {
    id: "s4",
    title: "Zarbali Drel va Perforatorlar",
    subtitle: "Beton, tosh va metallni oson yoruvchi yuqori quvvatli perforatorlar. To'liq komplekt bilan.",
    image_url: "https://images.unsplash.com/photo-1586864387967-d02ef85d93e8?q=80&w=1920&auto=format&fit=crop",
    button_text: "Perforatorlarni ko'rish",
    link: "/categories/perforatorlar",
    sort_order: 4,
    is_active: true,
    created_at: "2025-01-01T00:00:00.000Z",
  },
  {
    id: "s5",
    title: "4D Yashil Lazer Uravenlar",
    subtitle: "16 chiziqli, pultli va 360 daraja aniqlikdagi professional sath o'lchagichlar.",
    image_url: "https://images.unsplash.com/photo-1581092580497-e0d23cbdf1dc?q=80&w=1920&auto=format&fit=crop",
    button_text: "O'lchov asboblari",
    link: "/categories/lazer-uravenlar",
    sort_order: 5,
    is_active: true,
    created_at: "2025-01-01T00:00:00.000Z",
  },
];

export const DEFAULT_PROMOCODES: Promocode[] = [
  {
    id: "promo-uzo10",
    code: "UZO10",
    discount_type: "percent",
    discount_value: 10,
    min_order_amount: 1000000,
    max_discount_amount: 400000,
    usage_limit: 200,
    used_count: 0,
    expires_at: null,
    is_active: true,
    created_at: "2025-01-01T00:00:00.000Z",
  },
  {
    id: "promo-usta200",
    code: "USTA200",
    discount_type: "fixed",
    discount_value: 200000,
    min_order_amount: 2000000,
    max_discount_amount: null,
    usage_limit: null,
    used_count: 0,
    expires_at: null,
    is_active: true,
    created_at: "2025-01-01T00:00:00.000Z",
  },
];
